from models import (
    Asset,
    AttackPath,
    AttackPathStep,
    BusinessService,
    Exposure,
    MaturityDomain,
    RemediationAction,
    WorkshopArtifacts,
)


BUSINESS_SERVICES = [
    BusinessService(
        id="svc-payments",
        name="Digital Payments",
        description="Customer-facing payment authorization and settlement journey.",
        executive_owner="Chief Revenue Officer",
        business_owner="VP Payments Platform",
        criticality="Critical",
        risk_appetite="No validated critical path may remain open longer than 7 days.",
        customer_impact="Payment outage or tampering affects revenue, trust, and regulatory reporting.",
        revenue_dependency="Direct revenue capture for online channels.",
        crown_jewel_asset_ids=["asset-payment-api", "asset-customer-db"],
        in_scope=True,
        scope_reason="Highest revenue concentration and strongest attacker incentive.",
    ),
    BusinessService(
        id="svc-identity",
        name="Workforce Identity",
        description="SSO, privileged access, and identity governance for employees and contractors.",
        executive_owner="Chief Information Security Officer",
        business_owner="Director IAM",
        criticality="Critical",
        risk_appetite="Privileged identity exposure requires same-week validation and executive visibility.",
        customer_impact="Compromised identity can unlock lateral movement into customer data systems.",
        revenue_dependency="Indirect, but a failure enables enterprise-wide compromise.",
        crown_jewel_asset_ids=["asset-okta", "asset-pam"],
        in_scope=True,
        scope_reason="Identity is the most reusable control plane for attackers.",
    ),
    BusinessService(
        id="svc-platform",
        name="Cloud Delivery Platform",
        description="CI/CD, container runtime, and production cloud landing zone.",
        executive_owner="Chief Technology Officer",
        business_owner="VP Infrastructure",
        criticality="High",
        risk_appetite="Internet-reachable build or cloud control-plane exposures require rapid containment.",
        customer_impact="Platform compromise can introduce malicious code or expose customer data.",
        revenue_dependency="Supports all digital product delivery.",
        crown_jewel_asset_ids=["asset-ci", "asset-prod-vpc"],
        in_scope=True,
        scope_reason="Attack path bridge between engineering systems and production.",
    ),
    BusinessService(
        id="svc-marketing",
        name="Public Marketing",
        description="Corporate website, campaign microsites, analytics tags, and brand presence.",
        executive_owner="Chief Marketing Officer",
        business_owner="Director Digital Marketing",
        criticality="Medium",
        risk_appetite="Defacement and tracking exposure are managed on standard change windows unless chained.",
        customer_impact="Brand trust and lead-generation impact, limited sensitive data processing.",
        revenue_dependency="Indirect lead generation.",
        crown_jewel_asset_ids=[],
        in_scope=False,
        scope_reason="Tracked, but not part of the first crown-jewel CTEM sprint.",
    ),
]


ASSETS = [
    Asset(
        id="asset-payment-api",
        name="Payment Gateway API",
        type="Web Application",
        service_id="svc-payments",
        owner="Payments Engineering",
        environment="Production",
        criticality="Critical",
        crown_jewel=True,
        internet_exposed=True,
        reachable_from_internet="Direct",
        tags=["pci", "customer-facing", "api"],
    ),
    Asset(
        id="asset-customer-db",
        name="Customer Data Store",
        type="Database",
        service_id="svc-payments",
        owner="Data Platform",
        environment="Production",
        criticality="Critical",
        crown_jewel=True,
        internet_exposed=False,
        reachable_from_internet="Indirect",
        tags=["pii", "pci", "crown-jewel"],
    ),
    Asset(
        id="asset-okta",
        name="Workforce SSO Tenant",
        type="Identity Provider",
        service_id="svc-identity",
        owner="Identity Engineering",
        environment="Production",
        criticality="Critical",
        crown_jewel=True,
        internet_exposed=True,
        reachable_from_internet="Direct",
        tags=["sso", "mfa", "privileged-access"],
    ),
    Asset(
        id="asset-pam",
        name="Privileged Access Vault",
        type="Security Platform",
        service_id="svc-identity",
        owner="Security Engineering",
        environment="Production",
        criticality="Critical",
        crown_jewel=True,
        internet_exposed=False,
        reachable_from_internet="Indirect",
        tags=["privileged-access", "secrets"],
    ),
    Asset(
        id="asset-ci",
        name="Build Automation and CI Runners",
        type="CI/CD",
        service_id="svc-platform",
        owner="Developer Experience",
        environment="Shared Services",
        criticality="High",
        crown_jewel=True,
        internet_exposed=True,
        reachable_from_internet="Direct",
        tags=["source-code", "deployment", "supply-chain"],
    ),
    Asset(
        id="asset-prod-vpc",
        name="Production Cloud VPC",
        type="Cloud Network",
        service_id="svc-platform",
        owner="Cloud Platform",
        environment="Production",
        criticality="High",
        crown_jewel=True,
        internet_exposed=False,
        reachable_from_internet="Indirect",
        tags=["aws", "network", "production"],
    ),
    Asset(
        id="asset-marketing-site",
        name="Marketing Site",
        type="Web Application",
        service_id="svc-marketing",
        owner="Digital Marketing",
        environment="Production",
        criticality="Medium",
        crown_jewel=False,
        internet_exposed=True,
        reachable_from_internet="Direct",
        tags=["cms", "public-web"],
    ),
    Asset(
        id="asset-dev-wiki",
        name="Internal Engineering Wiki",
        type="Collaboration Tool",
        service_id="svc-platform",
        owner="Developer Experience",
        environment="Internal",
        criticality="Low",
        crown_jewel=False,
        internet_exposed=False,
        reachable_from_internet="Isolated",
        tags=["internal", "knowledge-base"],
    ),
]


EXPOSURES = [
    Exposure(
        id="exp-ci-token",
        title="Leaked deployment token in public repository",
        description="A token with deployment scope was discovered in a public code history fork.",
        exposure_type="Secret",
        asset_id="asset-ci",
        severity="Medium",
        cvss=None,
        epss_probability=0.42,
        kev_signal=False,
        ransomware_observed=False,
        identity_risk=5,
        control_gap=4,
        attack_path_proximity="Crown Jewel",
        remediation_effort="Low",
        evidence_confidence="High",
        evidence="Secret scanning reproduced the token pattern and confirmed active permissions in a sandboxed validation.",
        suggested_action="Revoke token, rotate downstream credentials, constrain runner permissions, and add deploy-token policy guardrails.",
    ),
    Exposure(
        id="exp-payment-edge",
        title="Exploited edge framework vulnerability on payment API",
        description="The payment API runs a vulnerable framework version with public exploit activity and internet reachability.",
        exposure_type="CVE",
        asset_id="asset-payment-api",
        severity="Critical",
        cvss=9.8,
        epss_probability=0.92,
        kev_signal=True,
        ransomware_observed=True,
        identity_risk=1,
        control_gap=3,
        attack_path_proximity="Crown Jewel",
        remediation_effort="Medium",
        evidence_confidence="High",
        evidence="External attack surface validation confirmed vulnerable version exposure without executing destructive payloads.",
        suggested_action="Apply emergency patch or virtual patch, validate WAF coverage, and retest externally.",
    ),
    Exposure(
        id="exp-okta-mfa",
        title="Privileged SSO group lacks phishing-resistant MFA",
        description="Contractor admin group can approve privileged sessions with push MFA only.",
        exposure_type="Identity",
        asset_id="asset-okta",
        severity="High",
        cvss=None,
        epss_probability=0.36,
        kev_signal=False,
        ransomware_observed=True,
        identity_risk=5,
        control_gap=5,
        attack_path_proximity="Same Service",
        remediation_effort="Medium",
        evidence_confidence="High",
        evidence="Identity posture review found 18 privileged users outside the phishing-resistant MFA policy.",
        suggested_action="Move privileged group to phishing-resistant MFA, require device posture, and retest access policy.",
    ),
    Exposure(
        id="exp-cloud-sg",
        title="Over-permissive security group bridges CI runners to customer data subnet",
        description="Shared CI runners can initiate traffic to the production data subnet through an inherited cloud rule.",
        exposure_type="Cloud",
        asset_id="asset-prod-vpc",
        severity="High",
        cvss=None,
        epss_probability=0.21,
        kev_signal=False,
        ransomware_observed=False,
        identity_risk=2,
        control_gap=5,
        attack_path_proximity="Crown Jewel",
        remediation_effort="Medium",
        evidence_confidence="Medium",
        evidence="Cloud graph analysis showed path reachability; packet-level validation is scheduled with platform approval.",
        suggested_action="Restrict CI runner egress, segment production data subnet, and add cloud policy-as-code checks.",
    ),
    Exposure(
        id="exp-marketing-hsts",
        title="HSTS missing on marketing site",
        description="Public marketing site does not enforce HSTS, creating downgrade risk for site visitors.",
        exposure_type="Control Gap",
        asset_id="asset-marketing-site",
        severity="Medium",
        cvss=5.3,
        epss_probability=0.08,
        kev_signal=False,
        ransomware_observed=False,
        identity_risk=0,
        control_gap=2,
        attack_path_proximity="None",
        remediation_effort="Low",
        evidence_confidence="High",
        evidence="Header scan confirmed HSTS is absent from production responses.",
        suggested_action="Add HSTS with preload-ready configuration through the CDN change workflow.",
    ),
    Exposure(
        id="exp-dev-wiki-cve",
        title="High CVSS library issue on isolated engineering wiki",
        description="A high-severity library issue exists on an internal wiki with no known exploit path to scoped services.",
        exposure_type="CVE",
        asset_id="asset-dev-wiki",
        severity="High",
        cvss=8.1,
        epss_probability=0.03,
        kev_signal=False,
        ransomware_observed=False,
        identity_risk=0,
        control_gap=1,
        attack_path_proximity="None",
        remediation_effort="High",
        evidence_confidence="Medium",
        evidence="Authenticated scanner confirmed version; network review shows no production reachability.",
        suggested_action="Patch in normal maintenance window and continue monitoring exploit intelligence.",
    ),
]


ATTACK_PATHS = [
    AttackPath(
        id="path-ci-to-data",
        name="Public secret to customer data path",
        objective="Use leaked CI deployment authority to reach the customer data subnet.",
        business_service_id="svc-payments",
        exposure_ids=["exp-ci-token", "exp-cloud-sg"],
        status="Validated",
        evidence_confidence="High",
        blast_radius="Potential write path into payment workloads and read path toward customer data services.",
        safe_validation_method="Token was validated in a sandboxed runner; network reachability was confirmed through graph analysis.",
        steps=[
            AttackPathStep(
                order=1,
                title="Acquire deployment token",
                asset_id="asset-ci",
                technique="MITRE ATT&CK: Unsecured Credentials",
                validation="Secret scanner and access review confirmed active deployment scope.",
                control_gap="No automatic revocation for public-code secret exposure.",
            ),
            AttackPathStep(
                order=2,
                title="Run deployment workflow",
                asset_id="asset-ci",
                technique="MITRE ATT&CK: Valid Accounts",
                validation="Sandbox confirmed token can trigger deployment workflow actions.",
                control_gap="Runner permissions are broader than the scoped service boundary.",
            ),
            AttackPathStep(
                order=3,
                title="Reach production data subnet",
                asset_id="asset-prod-vpc",
                technique="MITRE ATT&CK: Network Service Discovery",
                validation="Cloud graph shows CI-to-data-subnet path through inherited security group.",
                control_gap="Segmentation policy does not separate build infrastructure from production data plane.",
            ),
        ],
    ),
    AttackPath(
        id="path-sso-to-payments",
        name="Privileged SSO compromise to payment operations",
        objective="Compromise an admin session and alter payment operations configuration.",
        business_service_id="svc-payments",
        exposure_ids=["exp-okta-mfa"],
        status="Plausible",
        evidence_confidence="Medium",
        blast_radius="Privileged identity compromise could affect payment admin portals and deployment approvals.",
        safe_validation_method="Policy review and tabletop emulation; no live credential capture performed.",
        steps=[
            AttackPathStep(
                order=1,
                title="Phish privileged contractor",
                asset_id="asset-okta",
                technique="MITRE ATT&CK: Phishing",
                validation="MFA policy allows push approval for the affected group.",
                control_gap="Privileged identities are not uniformly bound to phishing-resistant MFA.",
            ),
            AttackPathStep(
                order=2,
                title="Approve privileged session",
                asset_id="asset-pam",
                technique="MITRE ATT&CK: Account Manipulation",
                validation="Tabletop confirmed approval chain relies on identity group membership.",
                control_gap="No compensating device trust requirement for contractors.",
            ),
        ],
    ),
]


MATURITY = [
    MaturityDomain(
        name="Scoping",
        score=2,
        target=4,
        current_state="Critical services are known informally, but scope is not refreshed with business owners.",
        next_step="Run a crown-jewel workshop with Payments, IAM, Platform, and GRC leaders.",
    ),
    MaturityDomain(
        name="Discovery",
        score=3,
        target=4,
        current_state="Scanner and cloud data exist, but identity and SaaS exposures are not normalized.",
        next_step="Create a single exposure taxonomy across CVE, cloud, identity, secrets, SaaS, and control gaps.",
    ),
    MaturityDomain(
        name="Prioritization",
        score=2,
        target=4,
        current_state="Teams still negotiate urgency from CVSS and asset tags.",
        next_step="Adopt CTEM decision outcomes with explicit business, threat, control, and validation drivers.",
    ),
    MaturityDomain(
        name="Validation",
        score=1,
        target=3,
        current_state="Pen tests happen periodically, but validation evidence is not tied to remediation decisions.",
        next_step="Define safe validation methods and evidence thresholds for Act and Attend decisions.",
    ),
    MaturityDomain(
        name="Mobilization",
        score=2,
        target=4,
        current_state="Tickets are created, but ownership, risk acceptance, and retest are inconsistent.",
        next_step="Create remediation SLAs, RACI, exception rules, and executive escalation paths.",
    ),
]


REMEDIATION_ACTIONS = [
    RemediationAction(
        id="ctem-101",
        exposure_id="exp-payment-edge",
        title="Patch or virtually patch payment API edge framework",
        owner="Payments Engineering",
        team="Application Platform",
        status="In Progress",
        priority="Act",
        sla="7 days",
        due_in_days=2,
        playbook="Emergency change with WAF validation, deploy canary, external retest, and business sign-off.",
        dependency="Change Advisory Board expedited approval",
        retest_status="Scheduled",
        risk_acceptance_required=False,
    ),
    RemediationAction(
        id="ctem-102",
        exposure_id="exp-ci-token",
        title="Revoke leaked deployment token and constrain CI permissions",
        owner="Developer Experience",
        team="Platform Security",
        status="To Do",
        priority="Act",
        sla="72 hours",
        due_in_days=1,
        playbook="Revoke token, rotate dependent secrets, scope deployment permissions, and add secret revocation automation.",
        dependency="Payments release owner to approve token rotation window",
        retest_status="Not Started",
        risk_acceptance_required=False,
    ),
    RemediationAction(
        id="ctem-103",
        exposure_id="exp-okta-mfa",
        title="Move privileged groups to phishing-resistant MFA",
        owner="Identity Engineering",
        team="IAM",
        status="To Do",
        priority="Attend",
        sla="14 days",
        due_in_days=9,
        playbook="Require hardware-backed MFA for privileged groups, publish exception path, and retest sign-in policy.",
        dependency="Contractor communications and hardware key distribution",
        retest_status="Not Started",
        risk_acceptance_required=True,
    ),
    RemediationAction(
        id="ctem-104",
        exposure_id="exp-cloud-sg",
        title="Segment CI runner egress from production data subnet",
        owner="Cloud Platform",
        team="Infrastructure",
        status="In Progress",
        priority="Attend",
        sla="14 days",
        due_in_days=6,
        playbook="Apply least-privilege egress rule, add policy-as-code guardrail, and rerun cloud reachability validation.",
        dependency="CI job inventory to avoid breaking production deployments",
        retest_status="Blocked",
        risk_acceptance_required=False,
    ),
    RemediationAction(
        id="ctem-105",
        exposure_id="exp-marketing-hsts",
        title="Enable HSTS on marketing site",
        owner="Digital Marketing",
        team="Web Operations",
        status="Done",
        priority="Monitor",
        sla="30 days",
        due_in_days=0,
        playbook="Apply CDN header policy and monitor browser preload readiness.",
        dependency="None",
        retest_status="Passed",
        risk_acceptance_required=False,
    ),
    RemediationAction(
        id="ctem-106",
        exposure_id="exp-dev-wiki-cve",
        title="Patch isolated engineering wiki library",
        owner="Developer Experience",
        team="Collaboration Services",
        status="Accepted Risk",
        priority="Track",
        sla="Standard maintenance",
        due_in_days=21,
        playbook="Patch in routine maintenance unless exploit activity or reachability changes.",
        dependency="Quarterly wiki upgrade window",
        retest_status="Not Started",
        risk_acceptance_required=True,
    ),
]


WORKSHOP_ARTIFACTS = WorkshopArtifacts(
    maturity_assessment=[
        "Score each CTEM stage from 1-5 using current evidence, not aspiration.",
        "Name the highest-friction handoff between security, IT, engineering, and business owners.",
        "Choose one metric that proves exposure reduction, not activity volume.",
    ],
    crown_jewel_worksheet=[
        "Name the business service and executive owner.",
        "Identify crown-jewel assets, privileged identities, and externally reachable paths.",
        "Define what exposure duration is unacceptable for this service.",
        "List resolver teams and change windows before prioritization begins.",
    ],
    prioritization_rationale=[
        "Start from business service impact and attacker path, then add vulnerability severity.",
        "Escalate known exploited, internet-reachable, or identity-amplifying exposures.",
        "Downgrade isolated findings when validation shows no plausible path to scoped services.",
    ],
    validation_evidence_pack=[
        "State the validation method and safety boundary.",
        "Capture exploitability, reachability, control performance, and blast radius evidence.",
        "Attach retest criteria to every Act or Attend remediation action.",
    ],
    raci=[
        {"role": "CISO", "responsibility": "Accountable for CTEM outcomes and risk acceptance policy."},
        {"role": "Business Owner", "responsibility": "Defines service criticality, impact tolerance, and remediation tradeoffs."},
        {"role": "Security Engineering", "responsibility": "Owns scoring logic, validation evidence, and exposure quality."},
        {"role": "Resolver Team", "responsibility": "Owns remediation delivery and retest readiness."},
        {"role": "GRC", "responsibility": "Tracks exceptions, control evidence, and executive reporting."},
    ],
    roadmap_30_60_90=[
        {
            "window": "30 days",
            "outcome": "Define scope and decision model",
            "actions": "Run crown-jewel workshop, publish exposure taxonomy, and agree on Act/Attend/Monitor/Track definitions.",
        },
        {
            "window": "60 days",
            "outcome": "Validate top exposure paths",
            "actions": "Normalize scanner/cloud/identity data, run safe validation on top paths, and attach evidence packs to tickets.",
        },
        {
            "window": "90 days",
            "outcome": "Mobilize and report exposure reduction",
            "actions": "Operationalize SLAs, risk acceptance, retest, executive dashboards, and recurring CTEM review cadence.",
        },
    ],
)
