from fastapi import APIRouter, Depends, Query
from fastapi.responses import HTMLResponse, StreamingResponse

from app.dependencies import get_data_service
from app.services.data_service import DataService

router = APIRouter(tags=["Executive Summary"])


@router.get("/api/executive-summary")
def executive_summary(format: str = Query("markdown", pattern="^(markdown|html)$"),
                      data: DataService = Depends(get_data_service)):
    prioritized = data.get_prioritized_exposures()
    services = data.get_business_services()
    assets = data.get_assets()
    maturity = data.get_maturity()
    attack_paths = data.get_attack_paths()

    act_items = [p for p in prioritized if p.decision == "Act"]
    attend_items = [p for p in prioritized if p.decision == "Attend"]
    scoped_services = [s for s in services if s.in_scope]
    validated_paths = [p for p in attack_paths if p.status == "Validated"]

    summary = _build_summary(
        organization="Northstar Financial Services",
        scoped_count=len(scoped_services),
        crown_jewel_count=len([a for a in assets if a.crown_jewel]),
        exposure_count=len(data.get_exposures()),
        act_count=len(act_items),
        attend_count=len(attend_items),
        validated_path_count=len(validated_paths),
        maturity_current=round(sum(d.score for d in maturity) / len(maturity), 1),
        maturity_target=round(sum(d.target for d in maturity) / len(maturity), 1),
        act_items=[(p.title, p.ctem_score, p.next_action) for p in act_items],
        attend_items=[(p.title, p.ctem_score, p.next_action) for p in attend_items],
    )

    if format == "html":
        html = summary.replace("\n", "<br>\n").replace("## ", "<h2>").replace("### ", "<h3>")
        html = f"<html><body style='font-family:system-ui,sans-serif;max-width:800px;margin:40px auto'>{html}</body></html>"
        return HTMLResponse(content=html)

    return StreamingResponse(
        iter([summary]),
        media_type="text/markdown",
        headers={"Content-Disposition": 'attachment; filename="ctem-executive-summary.md"'},
    )


def _build_summary(
    organization: str, scoped_count: int, crown_jewel_count: int, exposure_count: int,
    act_count: int, attend_count: int, validated_path_count: int,
    maturity_current: float, maturity_target: float,
    act_items: list[tuple[str, int, str]], attend_items: list[tuple[str, int, str]],
) -> str:
    lines = [
        f"# CTEM Executive Summary — {organization}",
        "",
        f"**Generated:** {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "## Program Overview",
        "",
        "| Metric | Value |",
        "| --- | --- |",
        f"| Scoped services | {scoped_count} |",
        f"| Crown-jewel assets | {crown_jewel_count} |",
        f"| Total exposures | {exposure_count} |",
        f"| Act decisions | {act_count} |",
        f"| Attend decisions | {attend_count} |",
        f"| Validated attack paths | {validated_path_count} |",
        f"| Maturity (current/target) | {maturity_current}/{maturity_target} |",
        "",
        "## Act Decisions — Immediate Mobilization",
        "",
    ]
    if act_items:
        for title, score, action in act_items:
            lines.append(f"- **{title}** (CTEM {score}): {action}")
    else:
        lines.append("*No Act decisions in the current view.*")
    lines.append("")

    if attend_items:
        lines.append("## Attend Decisions — Leadership Coordination")
        lines.append("")
        for title, score, action in attend_items:
            lines.append(f"- **{title}** (CTEM {score}): {action}")
        lines.append("")

    lines.extend([
        "## Exposure Reduction Goal",
        "",
        "35% validated critical-path reduction in 90 days.",
        "",
        "---",
        "",
        "*Generated by CTEM Leader Lab*",
        "",
    ])
    return "\n".join(lines)
